export const pathDefault = {
  homePage: "/",
  hostHomes: "/host/homes",
  hostExperiences: "host/experiences",
  help: "/help",
  signup: "/dang-ky",
  signin: "/dang-nhap",
  rentalRoomList: "/list-of-available-rooms-for-rent",
  rentalRoomDetail: "/room-rental-detail/:id",
  booking: "/booking",
  admin: "/admin",
  managerUser: "/admin/manager-user",
  managerLocation: "/admin/manager-location",
  informationPertional: "/information-pertional",
  adminLogin: "/admin-login",
};
